server:
  port: 8880

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/users?&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true