server:
  port: 8083

spring:
  application:
    name: quiz
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    solves: solves.exchange
  queues:
    solves-queue: solves.queue
  routing-keys:
    solves-key: solves.routing-key