server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect