server:
  port: 8086

spring:
  application:
    name: take-quiz
  datasource:
    url: jdbc:mysql://localhost:3306/takeQuiz?&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    results: results.exchange
  queues:
    results-queue: results.queue
  routing-keys:
    results-key: results.routing-key