server:
  port: 8084

spring:
  application:
    name: question
  data:
    mongodb:
      port: 27017
      host: localhost
      database: question
  rabbitmq:
    addresses: localhost:5672

rabbitmq:
  exchanges:
    del-quiz: del-quiz.exchange
  queues:
    del-quiz-questions-queue: del-quiz-questions.queue
  routing-keys:
    del-quiz-key: del-quiz.routing-key