server:
  port: 8088

spring:
  application:
    name: select-answer
  data:
    mongodb:
      port: 27017
      host: localhost
      database: selectanswer
  rabbitmq:
    addresses: localhost:5672